### ISSUE TITLE
`$ ember-fastboot fastboot-config.js`: TypeError: next is not a function

### ISSUE THREAD

**Issue by teckays** [ember-fastboot/ember-fastboot-server#7]
I'm trying to start FastBoot server from command line providing this config file:

**fastboot-config.js**
``` lang-js
module.exports = {
  port: 8000,
  appFile: "/app/app.js",
  vendorFile: "fastboot-dist/assets/vendor.js",
  htmlFile: "app/index.html"
};
```

and this is the output:
```
2015-12-29T06:57:16.243Z [Server 0] Server listening on port 8000
2015-12-29T06:57:16.252Z [Server 0] Starting rendering engine
2015-12-29T06:57:16.253Z [Renderer 0] Engine starting up (phantom)
/usr/local/lib/node_modules/ember-fastboot/lib/plugins/removeScriptTags.js:6
    next();
    ^

TypeError: next is not a function
    at Object.module.exports.beforeInit (/usr/local/lib/node_modules/ember-fastboot/lib/plugins/removeScriptTags.js:6:5)
    at next (/usr/local/lib/node_modules/ember-fastboot/lib/renderer.js:245:14)
    at PrerenderRenderer.pluginEvent (/usr/local/lib/node_modules/ember-fastboot/lib/renderer.js:252:3)
    at Request._callback (/usr/local/lib/node_modules/ember-fastboot/lib/renderer.js:36:13)
    at Request.self.callback (/usr/local/lib/node_modules/ember-fastboot/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/ember-fastboot/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```

Ember Version:
```
DEBUG: -------------------------------
DEBUG: Ember       : 2.4.0-canary+2d622f12
DEBUG: Ember Data  : 2.4.0-canary+24fdc95d73
DEBUG: jQuery      : 1.11.3
DEBUG: -------------------------------
Ember Inspector Active
```

**Comment by jasonmit** [comment]
ember-fastboot on npm is not the same as this project.  That project is ember-prerender and I am not really sure why they published as ember-fastboot.

This project is published under ember-fastboot-server

**Comment by teckays** [comment]
@jasonmit I didn't install `ember-prerender`, I installed https://github.com/tildeio/ember-cli-fastboot

**Comment by jasonmit** [comment]
The stack trace is pointing to ember prerender files under node_modules/ember-fastboot.  Like I said ember-prerender is published to npm also under the name ember-fastboot.

**Comment by teckays** [comment]
@jasonmit ouch! OK, now I understand what you meant! Thank you.

**Comment by tomdale** [comment]
Closing this. Hopefully we can work with the folks that published `ember-fastboot` to get this cleared up.

**Comment by jasonmit** [comment]
@tomdale he just unpublished if you want to register it

https://github.com/zipfworks/ember-prerender/issues/36#issuecomment-182542776
